FROM mambaorg/micromamba:2.1.1

ARG VERSION=1.0.0

USER root

## Install dependencies
RUN micromamba install -y -n base -c bioconda -c conda-forge \
    procps-ng \
    wget \
    tar \
    git \
    make \
    gxx \
    zlib \
    binutils \
    ## sambamba is not a dependency but is used downstream of bwa-plus in oncoanalyser
    "sambamba>=1.0.1" \
    && micromamba clean --all --yes

ENV PATH="/opt/conda/bin:/opt/conda/condabin:${PATH}"

## Download bwa-plus
RUN wget https://github.com/hartwigmedical/bwa-plus/archive/refs/tags/bwa-plus-v${VERSION}.tar.gz
RUN mkdir bwa-plus/ && \
    tar --extract --gzip --strip-components=1 --directory bwa-plus/ --file bwa-plus-v${VERSION}.tar.gz

## Add safestringlib external dependency
## It does not exist by default in the source code zip file auto-generated by GitHub
RUN cd bwa-plus/ext/ && \
    rm -rf safestringlib/ && \
    git clone https://github.com/intel/safestringlib && \
    cd safestringlib/ && \
    git checkout 245c4b8 ## Ensure updates to safestringlib do not break compilation

## Fix error "implicit declaration of function" when compiling safestringlib
RUN sed -i "1i#include <stdlib.h>" bwa-plus/ext/safestringlib/safeclib/abort_handler_s.c && \
    sed -i "1i#include <ctype.h>"  bwa-plus/ext/safestringlib/safeclib/strcasestr_s.c && \
    sed -i "1i#include <ctype.h>"  bwa-plus/ext/safestringlib/safeclib/strcasecmp_s.c

## Compile
RUN make -C bwa-plus/

## Move binary to final location and clean up
RUN chmod +x bwa-plus/bwa-plus* && \
    mv bwa-plus/bwa-plus* /usr/local/bin/ && \
    rm -r bwa-plus/ bwa-plus-v${VERSION}.tar.gz && \
    ln -sf /usr/local/bin/bwa-plus /usr/local/bin/bwa-mem2

## Add aliases
RUN for binary in /usr/local/bin/bwa-plus*; do \
        ln -sf $binary $(echo $binary | sed "s/bwa-plus/bwa-mem2/"); \
    done
